USE [master]
GO
/****** Object:  Database [ERPSystem]    Script Date: 04-10-2021 17:09:12 ******/
CREATE DATABASE [ERPSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ERPSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ERPSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ERPSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ERPSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ERPSystem] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ERPSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ERPSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ERPSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ERPSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ERPSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ERPSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [ERPSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ERPSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ERPSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ERPSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ERPSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ERPSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ERPSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ERPSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ERPSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ERPSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ERPSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ERPSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ERPSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ERPSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ERPSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ERPSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ERPSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ERPSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [ERPSystem] SET  MULTI_USER 
GO
ALTER DATABASE [ERPSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ERPSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ERPSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ERPSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ERPSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ERPSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ERPSystem', N'ON'
GO
ALTER DATABASE [ERPSystem] SET QUERY_STORE = OFF
GO
USE [ERPSystem]
GO
/****** Object:  Table [dbo].[Kunder]    Script Date: 04-10-2021 17:09:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kunder](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Fornavn] [nvarchar](50) NOT NULL,
	[Efternavn] [nvarchar](50) NOT NULL,
	[Postnummer] [int] NOT NULL,
	[By] [nvarchar](50) NOT NULL,
	[Vejnavn] [nvarchar](50) NOT NULL,
	[Husnummer] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Telefonnummer] [int] NOT NULL,
	[Kontaktinfo] [nvarchar](50) NULL,
	[PersonID] [int] NOT NULL,
 CONSTRAINT [PK_Kunder] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ordre]    Script Date: 04-10-2021 17:09:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ordre](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KundeID] [int] NOT NULL,
	[Dato] [datetime] NOT NULL,
	[Lokation] [nvarchar](50) NULL,
	[Status] [nvarchar](50) NULL,
 CONSTRAINT [PK_Ordre] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ordrelinjer]    Script Date: 04-10-2021 17:09:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ordrelinjer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VareID] [int] NOT NULL,
	[OrdreID] [int] NOT NULL,
	[Antal] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Varer]    Script Date: 04-10-2021 17:09:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Varer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Navn] [nvarchar](50) NOT NULL,
	[Lagerantal] [int] NULL,
	[Salgspris] [float] NOT NULL,
	[Købspris] [float] NOT NULL,
	[Lagerplads] [int] NOT NULL,
 CONSTRAINT [PK_Varer] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ordre]  WITH CHECK ADD  CONSTRAINT [FK_Ordre_Kunder] FOREIGN KEY([KundeID])
REFERENCES [dbo].[Kunder] ([ID])
GO
ALTER TABLE [dbo].[Ordre] CHECK CONSTRAINT [FK_Ordre_Kunder]
GO
ALTER TABLE [dbo].[Ordrelinjer]  WITH CHECK ADD  CONSTRAINT [FK_Ordrelinjer_Ordre] FOREIGN KEY([OrdreID])
REFERENCES [dbo].[Ordre] ([ID])
GO
ALTER TABLE [dbo].[Ordrelinjer] CHECK CONSTRAINT [FK_Ordrelinjer_Ordre]
GO
ALTER TABLE [dbo].[Ordrelinjer]  WITH CHECK ADD  CONSTRAINT [FK_Ordrelinjer_Varer] FOREIGN KEY([VareID])
REFERENCES [dbo].[Varer] ([ID])
GO
ALTER TABLE [dbo].[Ordrelinjer] CHECK CONSTRAINT [FK_Ordrelinjer_Varer]
GO
USE [master]
GO
ALTER DATABASE [ERPSystem] SET  READ_WRITE 
GO
